### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by RenzoTale88** [esrud/GONE#1]
Good morning,
I'm trying to run GONE on a dataset composet of ~22M variants for 190 different samples. These variants have been called on a scaffold level genome, and the contigs/scaffolds have been renamed numerically to facilitate allow it to be compatible with gone (e.g. contig1 = 1, contig3 = 2, contig123 = 3 etc.). 
Before running it, I generate a configuration file as follow:
```
#INPUT_PARAMETERS_FILE

########################################################

PHASE=2 ### Phase = 0 (pseudohaploids), 1 (known phase), 2 (unknown phase)
cMMb=1  ### CentiMorgans per Megabase (if distance is not available). For humans set cMMb=0 and distances are obtained from genetic data file
DIST=1  ### none (0), Haldane correction (1) or Kosambi correction (2)
NGEN=2000 ### Number of generations for which linkage data is obtained in bins
NBIN=400  ### Number of bins (e.g. 1000, so that each bin includes NGEN/NBIN generations)
MAF=0.0   ### Minimum allele frequency (0-1)
ZERO=1    ### 0: Remove SNPs with zeroes (1: allow for them)
maxNCHROM=-99  ### Maximum number of chromosomes to be analysed (-99 = all chromosomes)
maxNSNP=-99 ### Approx number of SNPs per chromosomes to be analysed (-99 = all SNPs)
hc=0.05   ### Maximum value of c analysed
REPS=40   ### Number of replicates to RUN GONE
threads=2  ### Number of threads (if -99 it uses all possible processors)

###################################################################
```
Basically the basic configuration, reducing the number of processors to the number of available in the job. 
Every time I run it, though, I come across a core dumped error:
```
script_GONE.sh: line 95: 65409 Segmentation fault      (core dumped) ./PROGRAMMES/MANAGE_CHROMOSOMES2 >> out  <<@
```
I've tried to recompile the code, but still came across the same errors. Could it be due to how the software handle the chromosomes? Can fact that I got many contigs/scaffolds be the source of the issue?

Thank you in advance
Andrea

**Comment by armando-caballero** [comment]
Dear Andrea,
I understand that you use contigs in the place of chromosomes (no problem but, how many contigs you have?). On the other hand, if you are trying to run with 22 M SNPs, this is not feasible. The maximum allowed is about 50,000 SNPs per chromosome. Please change the command to:
maxNSNP=50000 ### Approx number of SNPs per chromosomes to be analysed (-99 = all SNPs).
Also, please first run the example provided to see there are no other system incompatibilities.Please let me know your progresses.
Best wishes,
Armando.

**Comment by RenzoTale88** [comment]
@armando-caballero thank you for your quick reply. After limiting to the larger, I have a total of 130 sequences used to call variants. The test seems to be working fine, manages to break the file and run the LD calculation stage just now. Should I limit to less chromosomes?

**Comment by armando-caballero** [comment]
I think it should work for 130 "chromosomes". If you have problems let me know.

**Comment by armando-caballero** [comment]
Wait. I fixed a maximum of 100 chromosomes. I will change the programme MANAGE_CHROMOSOMES.c to allow more.

**Comment by RenzoTale88** [comment]
@armando-caballero thank you very much for this, let me know when clone the software again and restart the analyses. In the meanwhile, I'm limiting to the very large contigs (tens of megabases) since I'm expecting them to be the most relevant anyway.

**Comment by RenzoTale88** [comment]
@armando-caballero I can confirm that after reducing to 50K varaints and to the largest 45 contigs, I can start the analysis. Currently running. Thank you very much for your help anyway!

**Comment by armando-caballero** [comment]
Andrea,
I have modified the first programme (MANAGE_CHROMOSOMES2) to allow for a maximum of 200 chromosomes and a maximum of 100K SNPs per chromosome. I am checking myself with some data but you may also try it if you wish.
However, I advise you to do first a "quick" run with say 10,000 SNPs per chromosomes to see if all goes well, because a run with 100K per chromosome takes quite a lot of time.
Note that the maximum of 100K is a sample at random of all your positions. If you have monomorphic positions, the actual number used will be lower. The best thing, therefore, is to have only SNPs (i.e. non-monomorphic data) in your sample.

**Comment by RenzoTale88** [comment]
Thank you Armando, right now the software is running with 50K markers and 45 chromosomes. After this will be over, I'll re-run it with the newer version of the code and test it.
Thanks again for the quick reply and support!

Andrea

**Comment by RenzoTale88** [comment]
@armando-caballero the run of GONE failed with an error I am not sure how to overcome. The log file produced the following output:
```
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 155689 seconds
Running GONE
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
GONE Ne estimated for aequinoctialis
```

and the error file looks like this:
```
 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1.



 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
mv: cannot stat ‘outfileLD_Ne_estimates’: No such file or directory
mv: cannot stat ‘outfileLD_d2_sample’: No such file or directory
```

I'm not sure how to specify the sample size. Is it a problem in my configuration file?
```
#INPUT_PARAMETERS_FILE

########################################################

PHASE=2 ### Phase = 0 (pseudohaploids), 1 (known phase), 2 (unknown phase)
cMMb=1  ### CentiMorgans per Megabase (if distance is not available). For humans set cMMb=0 and distances are obtained from genetic data file
DIST=1  ### none (0), Haldane correction (1) or Kosambi correction (2)
NGEN=2000 ### Number of generations for which linkage data is obtained in bins
NBIN=400  ### Number of bins (e.g. 1000, so that each bin includes NGEN/NBIN generations)
MAF=0.0   ### Minimum allele frequency (0-1)
ZERO=1    ### 0: Remove SNPs with zeroes (1: allow for them)
maxNCHROM=-99  ### Maximum number of chromosomes to be analysed (-99 = all chromosomes; maximum number is 200)
maxNSNP=100000 ### Maximum approx number of SNPs per chromosomes to be analysed
hc=0.05   ### Maximum value of c analysed
REPS=40   ### Number of replicates to RUN GONE
threads=4  ### Number of threads (if -99 it uses all possible processors)

###################################################################
```

Thanks again for the help

Andrea

**Comment by armando-caballero** [comment]
Dear Andrea,
I am sorry you still have problems. This is an error message by GONE which suggests that the input for this program has some error. I can see that the previous analyses run till the end, though it took 43 hours: CHROMOSOME ANALYSES took 155689 seconds.
The input for GONE is at the end of the file PARAMETERS_$FILE. Can you please send me that file so that I try to see what was wrong?
 Armando.

**Comment by RenzoTale88** [comment]
No need to worry Armando, instead thanks so much for your quick reply and help!
So, the last lines of the file are the following:
```
INPUT FOR GONE


0       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)
-nan       sample size (individuals; corrected for zeroes)
-nan       Hardy-Weinberg deviation
```

Not sure why it is creating nan as values.

**Comment by armando-caballero** [comment]
Hi,
Clearly the input is wrong. It should be:

2 IF PHASE IS UNKNOWN       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)
YOUR_SAMPLE SIZE       sample size (individuals; corrected for zeroes)
A VALUE CLOSE TO ZERO      Hardy-Weinberg deviation

The problem can be a crash of space/memory in some vector/matrix .... If you have 130 chromosomes and 100,000 SNPs per chromosome, that means: 5 x 10^9 pairs of SNPs per chromosome, and combining them, 6.5 x 10^11 pairs !!!
I suggest you to run a case with 10,000 SNPs (or perhaps 20,000) per chromosome and 130 chromosomes to check that all is right. Because of the large number of chromosomes this is more than enough. If works well then you can make replicates: Run it several times with 10,000 pairs of SNPs (in each replicate these SNPs will be taken at random).
Armando.

**Comment by RenzoTale88** [comment]
@armando-caballero thanks for your help, I'll try to do the changes you suggested and then come back to you!
Cheers
Andrea

**Comment by RenzoTale88** [comment]
@armando-caballero running with 10K markers seems to have successfully finished! Thank you very much for your help, I'll try increasing the number of variants per chromosomes and see when I will "break" it again. Thanks a lot for your help :)
