### ISSUE TITLE
Error on sample size number

### ISSUE THREAD

**Issue by kostasgalexiou** [esrud/GONE#11]
Hi,

I am running gone on the following ped and map files:

```
file.ped

1 Ai 0 0 0 -9 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 Alnem 0 0 0 -9 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 Ardechoise 0 0 0 -9 0 0 0 0 G G A A G G 0 0 G G
...
1 S3067 0 0 0 -9 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 Baurons 0 0 0 -9 0 0 0 0 0 0 A A G G 0 0 0 0
1 Dlargueta 0 0 0 -9 0 0 0 0 G A A A G G G G G G


file.map

1 1_583 0 583
1 1_585 0 585
1 1_593 0 593
...
8 8_20427213 0 20427213
8 8_20427252 0 20427252
8 8_20427274 0 20427274


```
Both files are space-separated and ped file contains only SNPs. The error I am getting is the following: 

(note: at a [previous issue](https://github.com/esrud/GONE/issues/9#issue-1213267404) this error was caused due to the presence of INDELs in the data, which is not the case here).

Thanks in advance 

```
+ bash ./GONE/Linux/script_GONE.sh 50lines_noOUT-noWebiiFenz.plink
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 47 seconds
Running GONE
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: no se puede efectuar `stat' sobre «outfileLD_Ne_estimates»: No existe el fichero o el directorio
mv: no se puede efectuar `stat' sobre «outfileLD_d2_sample»: No existe el fichero o el directorio
```

**Comment by armando-caballero** [comment]
Dear Kostas,
I can see you have very many zeroes (ungenotyped SNPs). It is possible that this is causing some problems. On how many SNPs and individuals do you have information? Can you give some details to try find what is going on?
Best wishes,
Armando

**Comment by kostasgalexiou** [comment]
Hi Armando,

Below is the percentage of missing data, in respect to the total number of SNPs for 46 lines.

6,61
6,65
7,71
7,75
7,93
8,02
8,14
8,20
8,44
8,68
8,75
8,83
9,01
9,02
9,14
9,25
9,28
9,38
9,54
9,59
9,63
9,67
10,00
10,32
10,64
10,83
11,43
11,69
14,16
16,16
19,71
20,14
20,33
20,68
24,00
25,17
32,05
37,76
37,90
38,18
40,23
47,88
50,94
90,77
91,89
98,28

I have removed the last 3 lines, but still getting the same error. I have also pasted below the output log of GONE.

TOTAL NUMBER OF SNPs
43


HARDY-WEINBERG DEVIATION
0.907148       Hardy-Weinberg deviation (sample)
0.909075       Hardy-Weinberg deviation (population)


CHROMOSOME 1
 NIND(real sample)=46
 NSNP=103938
 NSNP_calculations=3
 NSNP_+2alleles=103935
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.886321
 F_dev_HW (pop)=0.888654
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 2
 NIND(real sample)=46
 NSNP=87019
 NSNP_calculations=5
 NSNP_+2alleles=87014
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.581529
 F_dev_HW (pop)=0.588756
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 3
 NIND(real sample)=46
 NSNP=69002
 NSNP_calculations=3
 NSNP_+2alleles=68999
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.867059
 F_dev_HW (pop)=0.869760
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 4
 NIND(real sample)=46
 NSNP=61635
 NSNP_calculations=3
 NSNP_+2alleles=61632
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.739234
 F_dev_HW (pop)=0.744177
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 5
 NIND(real sample)=46
 NSNP=54736
 NSNP_calculations=4
 NSNP_+2alleles=54732
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=0.166667
 F_dev_HW (sample)=1.000000
 F_dev_HW (pop)=1.000000
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 6
 NIND(real sample)=46
 NSNP=68350
 NSNP_calculations=11
 NSNP_+2alleles=68338
 NSNP_zeroes=0
 NSNP_monomorphic=1
 NIND_corrected=-nan
 freq_MAF=0.222222
 F_dev_HW (sample)=1.000000
 F_dev_HW (pop)=1.000000
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 7
 NIND(real sample)=46
 NSNP=65413
 NSNP_calculations=7
 NSNP_+2alleles=65406
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.974313
 F_dev_HW (pop)=0.974864
 No genetic distances; using 1.000000 cM per Mb

CHROMOSOME 8
 NIND(real sample)=46
 NSNP=51646
 NSNP_calculations=7
 NSNP_+2alleles=51639
 NSNP_zeroes=0
 NSNP_monomorphic=0
 NIND_corrected=-nan
 freq_MAF=1.000000
 F_dev_HW (sample)=0.971671
 F_dev_HW (pop)=0.972278
 No genetic distances; using 1.000000 cM per Mb



INPUT FOR GONE


2       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)
0.000000       sample size (individuals; corrected for zeroes)
0.907148       Hardy-Weinberg deviation

**Comment by kostasgalexiou** [comment]
Dear Armando,

Yes, you are right. I had noticed it as well. I will close this issue and check thoroughly the data before opening a new issue.

Thanks
Kostas
