### ISSUE TITLE
Generation maximum

### ISSUE THREAD

**Issue by OKersten** [esrud/GONE#12]
Hi,

GONE is running great for me (what a cool tool) but I thought I open an issue as it might be interesting to other users as well.

I was wondering why the "interpretable"/"robust" cutoff lies at 200-300 generations back in time? When I am running GONE, I get values up to 600 generations back in time and they actually overlap wonderfully with other demographic history reconstruction analyses based on other underlying trends in the data (SFS or heterozygosity). 
I tried to find more information in the GONE publication or tutorial here, but couldn't find an answer to my question.

Cheers,
Oliver

**Comment by armando-caballero** [comment]
Dear Oliver,
The method is supposed to be more precise for more recent generations than for more distant ones, that is why we recommended to rely on the first 100-200 generations. However, this does not mean that estimations from further generations should always be discarded. If, as in yuor case, you have alternative information regarding more distant generations and this agrees with the estimations from GONE, this is reassuring. The only message we give is that for 100-200 generations you may "trust" the results. For more distant ones you should be mre cautious.
Best wishes,
Armando
