### ISSUE TITLE
Error running my data

### ISSUE THREAD

**Issue by qinshengyuan** [esrud/GONE#14]
Hi,

i got this error, "Wrong data type. Probably some input values are out of range".
but I didn't change any parameters except the hc to 0.01.
and when i use the map file which contain over 30 million SNP, it will fail to generate the outfileLD......

thanks 
Qin

**Comment by armando-caballero** [comment]
Dear Qin,
Maybe your data does not contain enough pairs of SNPs with c < 0.01.
With respect to the other issue, please read the TUTORIAL. You will find:
"Do not try to run data sets with more than, say, ten million SNPs (the maximum number of SNPs per chromosome is 1 million)"
Best wishes,
Armando.

**Comment by qinshengyuan** [comment]
> 



> Dear Qin, Maybe your data does not contain enough pairs of SNPs with c < 0.01. With respect to the other issue, please read the TUTORIAL. You will find: "Do not try to run data sets with more than, say, ten million SNPs (the maximum number of SNPs per chromosome is 1 million)" Best wishes, Armando.

Thanks a lot !

**Comment by qinshengyuan** [comment]
> Dear Qin, Maybe your data does not contain enough pairs of SNPs with c < 0.01. With respect to the other issue, please read the TUTORIAL. You will find: "Do not try to run data sets with more than, say, ten million SNPs (the maximum number of SNPs per chromosome is 1 million)" Best wishes, Armando.

Thank you very much!

**Comment by qinshengyuan** [comment]
Dear  armando:
I got this results when i using the hc=0.05, a  huge drop was detected in recent 5 generations, but  i don't think  there are subpopulations in my data. Should i abandon the results of of recent 5 geneations ? 


Thanks 
Qin

**Comment by armando-caballero** [comment]
If you do not expect such a recent drop I think it may be an artifact. Perhaps you have recent admixture even if you do not know it. Yes, you might disregard the initial generations. 
Best wishes,
Armando.
