### ISSUE TITLE
GONE not recognizing multiple samples

### ISSUE THREAD

**Issue by Hjorvik** [esrud/GONE#15]
Hi! I'm trying to run GONE with some sheep data, but every time I get this message: 
` DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 122 seconds
Running GONE
 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.
 Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1. Specify a sample size larger than 1. Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.

 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
 Specify a sample size larger than 1.
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 1 seconds
END OF ANALYSES `

I´m running GONE with 18 samples and the ped file looks like this:

1 sheep1 0 0 0 -9 T C
1 sheep2 0 0 0 -9 T C
1 sheep3 0 0 0 -9 T C
1 sheep4 0 0 0 -9 C C
1 sheep5 0 0 0 -9 T C
1 sheep6 0 0 0 -9 T C
1 sheep7 0 0 0 -9 T C
1 sheep8 0 0 0 -9 C C
1 sheep9 0 0 0 -9 C C
1 sheep10 0 0 0 -9 T C

and map like this:

1 SNP2 0.0026509423 8491
1 SNP3 0.0026553132 8505
1 SNP4 0.002656562 8509
1 SNP5 0.0026684259 8547
1 SNP6 0.0046050406 14750
1 SNP7 0.004607226 14757
1 SNP8 0.0046094114 14764
1 SNP9 0.0049481551 15849
1 SNP10 0.004954087 15868
1 SNP11 0.0051151854 16384

Any idea of what can be causing this?

**Comment by armando-caballero** [comment]
Hi,
I assume that when you write:
1 sheep1 0 0 0 -9 T C
you mean
1 sheep1 0 0 0 -9 T C etc.
Because with one SNP it is not possible to estimate Ne LD.
Otherwise, it looks fine to me fine. If you like, please send me a small ped and map files and I will check.
Best wishes,
Armando.

**Comment by Hjorvik** [comment]
Yes, I just copied the first SNP for brevity. Does the method truncate long names? I have also changed the names in the question. 
The names in the dataset are 18 digit codes for country of origin, breed, sex and 12 numbers.

**Comment by armando-caballero** [comment]
Code lengths should not matter. If you send me (armando@uvigo.es) a map and a ped with say 2-3 individuals I may try to see what the problem is.
Armando

**Comment by Hjorvik** [comment]
Hi Armando, thank you for your early answer. I have been able to fix the issue. The problem seems to be that there were too many snps (and some indels). Adding `--snps-only` and `--thin-count 10000000` to the plink command for generating the data was enough to solve it.
