### ISSUE TITLE
Segmentation fault & argument list too long

### ISSUE THREAD

**Issue by johannanvs** [esrud/GONE#17]
Hi,

I'm trying to run GONE with my data but get a whole bunch of error messages, starting with a segmentation fault. My data is not mapped to a chromosome-leveled reference genome, so instead I have thousands of scaffolds. However, I did put maxNCHROM=5 and maxNSNP=10000 as an initial test. These are the error messages I get:

```
DIVIDE .ped AND .map FILES IN CHROMOSOMES
Linux/script_GONE.sh: line 99:   936 Segmentation fault      (core dumped) ./PROGRAMMES/
MANAGE_CHROMOSOMES2 >> out  <<@
-99
$maxNSNP
@

Linux/script_GONE.sh: line 101: /usr/bin/rm: Argument list too long
RUNNING ANALYSIS OF CHROMOSOMES ...
cp: cannot stat ‘chromosome*’: No such file or directory
xargs: bash: terminated by signal 11
CHROMOSOME ANALYSES took 0 seconds
mv: cannot stat ‘chrom*’: No such file or directory
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file  Format error in file outfileLDoutfileLD

 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file  Format error in file outfileLDoutfileLD

 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat ‘outfileLD_Ne_estimates’: No such file or directory
mv: cannot stat ‘outfileLD_d2_sample’: No such file or directory
```

Any insights into why I am getting a segmentation fault and a "Argument list too long" error message would be highly appreciated!

Sincerely,
Johanna

**Comment by armando-caballero** [comment]
Dear Johanna,
If you have thousands of scaffolds do not try using a map with those thousands of  "chromosomes" and then put maxNCHROM=5. Rather, make a new data.map with only the first 5 scaffolds numbered 1, 2, 3, 4 and 5.
Try that.
Best wishes,
Armando

**Comment by johannanvs** [comment]
Thank you Armando for you quick reply! It worked with a new data.map with fewer scaffolds.

Cheers,
Johanna

**Comment by XIAO2Mark** [comment]
Hi Armando,

i also got same problems when i runing GONE, and i only had 26 chromosomes, the data.map is correct. can you help me to check it? details as bellow,

*************************************************************88
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 4 seconds
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory

many thx.

mark

**Comment by armando-caballero** [comment]
Dear Mark,
I canot tell you what is wrong unless I can see the files and more details. Please check that the requirements in the tutorial are met: format as explained, no more than 10 million SNPs, etc.
With best wishes,
Armando.

**Comment by SimonaSecomandi** [comment]
Hi all, I have the same issue and I can't figure out what's wrong. I have 46 chromosomes and 12,649,042 SNPs. Could the fact that I have 12 millions SNPs be the problem? If so, how can I run GONE with my data? 

Here's the error:

```
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 54 seconds
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file  Format error in file outfileLD Format error in file outfileLD
outfileLD

Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample'
```

Here's how my .map file look like:

```
1	SNP0	0	1000002
1	SNP1	0	1000020
1	SNP2	0	10000242
1	SNP3	0	10000293
1	SNP4	0	10000520
1	SNP5	0	10000526
1	SNP6	0	1000071
1	SNP7	0	1000076
1	SNP8	0	1000077
1	SNP9	0	1000094
```

and here's how my .ped file looks like:

```
AR93139 AR93139 0 0 0 -9 G G C C C C G G T C G A G G G C 0 0 0 0 A A C G T T T T A A A G C C C T T T A T 0 0 G C G G G G T T A G G A G C T T C C T C A G C C G C T C C C G T C C C T G T T C G A C A G G G G T C T A T G T T C C G G G G C A T T 0 0 C A A G 0 0 C C 0 0 T G C C C C T T T T C C C C C C C C T T C C C C C C C C 0 0 G G A A C C G G C C C C G G A A T T T T G G G G G G C C A A T T G G C C C C G G A A T T A A T T G G C C C C C C A A G G G G A A T T A A C
 C T T C C A A A A G G C C G G C C C C G G C C C C C C G G T T C C C C C C C C G G G G C C G G G G C C G G G G G G C C G G T T T T T T T T C C A A C C T T A A T T A A A A T T C C A A C C T T T T T T G G A A G G C C C C C C G G G G T T C C G G G G T T T T T T G G C C G G T T A A T T G G C C T T T T G G T T C....
```

Many thanks!!!

**Comment by armando-caballero** [comment]
Please read the Tutorial and the  user´s guide. You will find there:
Maximum number of SNPs per chromosome: 1 million
Maximum number of SNPs per genome: 10 million

Best wishes,
Armando.

**Comment by SimonaSecomandi** [comment]
Hi Armando, many thanks for your answer. Actually, my total SNPs number is 12 million, but I set the maxNSNPs parameter in the INPUT_PARAMETERS_FILE as 50,000 , which is the maximum (as said in the file itself):

`"maxNSNP=50000 ### Maximum approx number of SNPs per chromosomes to be analysed (maximum number is 50000)"
`
Having 46 chrs, assuming they all have 50,000 SNPs available, the total would be 2.3 millions.
Am I doing the calculations wrong? Is GONE considering the 12 million SNPs anyway?

Thanks again!
All the best,
Simona

**Comment by armando-caballero** [comment]
No. Your input data (map and ped) SHOULD NOT HAVE MORE THAN 10 MILLIONS.
And then, if you set up 50000 per chromosome, the estimation will be made with 2.3 millions.
Kind Regards,
Armando.

**Comment by SimonaSecomandi** [comment]
Ok I got it.. many thanks. I need to use another software then, or can I made a subset before running GONE? WHat do you think?

Many thanks again!
Best,
Simona
