### ISSUE TITLE
Ceiling or maximum Ne

### ISSUE THREAD

**Issue by andreaswallberg** [esrud/GONE#20]
Dear developers,

I am running GONE on organisms with large Ne, and Ne-inferences tend to pile up close to 4-5 M. I checked to code for indications of constants being set to variables that would indicate a maximum Ne, but I did not find any conclusive indications myself.

Is there a maximum Ne or similar ceiling being set somewhere in the code, or is there some other variable one could change to allow the algorithm to scale higher for Ne?

**Comment by armando-caballero** [comment]
Dear Andreas,
The maximum Ne considered is 10 millions. Please note that the accuracy of the method (any Ne estimation method) for such large numbers must be low.
Kind regards,
Armando
