### ISSUE TITLE
more SNPs than GONE allowed, and should sex Chr be removed during analysis?

### ISSUE THREAD

**Issue by QianghuiZhu** [esrud/GONE#25]
Hi! GONE is a great programe for Recent demographic history inferred!

I have some question while use GONE, could you give me some suggestions?

**Q1**: User's guide points that Max SNPs for per Chr is 1 million and Max SNPs for genome is 10 milion. What should I do if I have 33 million SNPs on genome and more than 1 million SNPs on per Chr? 
May I filtered MAF and geno missing? But I noticed that just keep all SNPs is OK (https://github.com/esrud/GONE/issues/23).
![image](https://github.com/esrud/GONE/assets/77773766/9fc5f1c5-ded7-4aee-971a-6e0964fb226b)

**Q2**: Should I remove sex Chr since it has different inheritance strategy compared with autosome?

With great thanks to you.

**Comment by armando-caballero** [comment]
Q1: use plink to randomly select a subset of SNPs as desired
Q2: GONE does not analyse X chromosome at the moment.
Aramndo

**Comment by QianghuiZhu** [comment]
Thanks for this!
