### ISSUE TITLE
backward in time

### ISSUE THREAD

**Issue by cfz1998** [esrud/GONE#26]
Hi! @esrud  @armando-caballero 
What's the meaning of "backward in time"? Does the `Generation 1`  in  `Output_Ne_example` mean present？
Thank you for your reply！

--CFZ

**Comment by armando-caballero** [comment]
Yes. Generations 1, 2, 3, 4 .... are generations back in the past.
Best wishes,
Armando.

**Comment by cfz1998** [comment]
Thanks! Have a good day!
--CFZ
