### ISSUE TITLE
LD_SNP_REAL3 breaks if sample name contains string "-9"

### ISSUE THREAD

**Issue by jessicachung** [esrud/GONE#3]
When LD_SNP_REAL3 reads a ped file to get genotypes, it looks for the first "-9" string to begin. Usually this is fine if that "-9" is the last phenotype column, but if the sample has "-9" in its name (e.g. "sample-9"), the genotypes read will be incorrect.

**Comment by armando-caballero** [comment]
Yes, sorry. The string "-9" is looked for in the file to start the reading of genotypes. So any other string "-9" will cause trouble. Please change that "-9" in your sample name by any other, e.g. "sample_9".

**Comment by armando-caballero** [comment]
Hi,
The problem of the string "-9" is solved. Now you do not need that string to read the genotypes and any string "-9" in your pedfile will not cause problems. Thank you for pointing this out.
