### ISSUE TITLE
 Specify a valid code for type of genotyping data (0, 1 or 2).

### ISSUE THREAD

**Issue by auNathalie** [esrud/GONE#30]
Hi, 
Thank you so much for developing this cool tool! - I'm very excited to get estimating with it. 

However, I'm running into a bit of an issue. 
_________________________________________________________
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
xargs: bash: terminated by signal 11
CHROMOSOME ANALYSES took 18 seconds
Running GONE
 Specify a valid code for type of genotyping data (0, 1 or 2). Specify a valid code for type of genotyping data (0, 1 or 2).
 ... (repeated line)....
 Specify a valid code for type of genotyping data (0, 1 or 2).
 Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 8 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory
__________________________________________________________________

I can't figure out why this information is lacking and where to input this information, if not in the INPUT_PARAMETERS_FILE.
It should be noted, that your provided example files run smoothly and beautifully when I try.

I'm using Linux, and have tried to run the script_GONE.sh on: 

This ped file: 
$ awk '{for (i=1; i<=30; i++) printf "%s ", $i; print ""}' snp_Aglais_urticae_2022.ped
J_2022 AgUr_01_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_02_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_03_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_04_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_05_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_06_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_07_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_08_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_09_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
J_2022 AgUr_10_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_11_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_12_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_13_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_14_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_15_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_16_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_17_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_18_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_19_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 
S_2022 AgUr_20_S_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A 

The map file: 
$ head snp_Aglais_urticae_2022.map
17 snp0 0 1569404
17 snp1 0 2142029
17 snp2 0 2142030
17 snp3 0 2142031
17 snp4 0 2142032
17 snp5 0 2142033
17 snp6 0 2142034
17 snp7 0 2142035
17 snp8 0 2142036
17 snp9 0 2142037

$ tail snp_Aglais_urticae_2022.map
32 snp106205659 0 8149593
32 snp106205660 0 8149594
32 snp106205661 0 8149595
32 snp106205662 0 8149596
32 snp106205663 0 8149597
32 snp106205664 0 8149598
32 snp106205665 0 8149599
32 snp106205666 0 8149600
32 snp106205667 0 8149601
32 snp106205668 0 8149602

With your provided INPUT_PARAMETERS_FILE:

#INPUT_PARAMETERS_FILE
########################################################

PHASE=2 ### Phase = 0 (pseudohaploids), 1 (known phase), 2 (unknown phase)
cMMb=1  ### CentiMorgans per Megabase (if distance is not available in map file).
DIST=1  ### none (0), Haldane correction (1) or Kosambi correction (2)
NGEN=2000 ### Number of generations for which linkage data is obtained in bins
NBIN=400  ### Number of bins (e.g. if 400, each bin includes NGEN/NBIN = 2000/400 = 5 generations)
MAF=0.0   ### Minor allele frequency (0-1) (recommended 0)
ZERO=1    ### 0: Remove SNPs with zeroes (1: allow for them)
maxNCHROM=-99  ### Maximum number of chromosomes to be analysed (-99 = all chromosomes; maximum number is 200)
maxNSNP=50000 ### Maximum approx number of SNPs per chromosomes to be analysed (maximum number is 50000)
hc=0.05   ### Maximum value of c analysed (recommended 0.05; maximum is 0.5)
REPS=40   ### Number of replicates to run GONE (recommended 40)
threads=-99  ### Number of threads (if -99 it uses all possible processors)

###################################################################

I hope to hear from you, 
Thank you. 

Best, 
Nathalie

**Comment by armando-caballero** [comment]
Dear Nathalie,
Two things:

(1) Add "1" as a first column in the ped file, i.e.
1 J_2022 AgUr_01_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A

(2) The ped file should start with chromosome 1 instead of 17, i.e.
1 snp0 0 1569404
1 snp1 0 2142029
..................................

Best wishes,
Armando.

**Comment by auNathalie** [comment]
Hi Armando,
Thank you so much for the fast reply! 
______________________________________________________________________________________________
1) 
I was not able to run it with a ped file like this: 
1 J_2022 AgUr_01_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A

I got this error: 
"Specify a sample size larger than 1." 

- I figured it took the population identifier as the ID.
 
Running with a ped file like this: 
1 AgUr_01_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A
1 AgUr_02_J_2022 0 0 0 -9 A A A A T T A A G G T T T T A A T T A A T T A A

- Worked beautifully! - I will separate my samples into population peds and run them individually. Thank you. 
  
2) 
I sorted my vcf before creating the ped and map with plink. Thank you for the heads up!
____________________________________________________________________________________________________

I can not wait to get plotting and see the recent population trends ! 

Again thank you so much for this great tool and all your help. 

Have a great weekend! 

Best, 
Nathalie
