### ISSUE TITLE
Impossible to run on MacOS X - Mac M1Pro

### ISSUE THREAD

**Issue by ltalignani** [esrud/GONE#32]
Dear all,

I have tried to run GONE on my MacBook Pro M1 pro. I followed the tutorial provided and changed the permissions of the entire folder recursively with the command` chmod -R 755 MacOSX/`.

I tried to run the program : `./script_GONE.sh example`. 
 
After receiving numerous alerts telling me that the developer was not identified, and allowing the program to be launched anyway via the system preferences, Gone finally launched, but the example provided did not work: 

```
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 0 seconds
Running GONE
 Too few bins.
 Too few bins. Too few bins.
 Too few bins.

 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins. Too few bins.

 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins. Too few bins.

 Too few bins.
 Too few bins.
 Too few bins.
 Too few bins. Too few bins.

 Too few bins.
 Too few bins.
 Too few bins.
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: rename outfileLD_Ne_estimates to Output_Ne_example: No such file or directory
mv: rename outfileLD_d2_sample to Output_d2_example: No such file or directory 
```

What can I do to correct that problem?

EDIT: I tried on my on dataset and obtained the same result. The .map and .ped files are in the MacOSX directory.

**Comment by esrud** [comment]
Dear Italignani,

GONE was originally developed for MacOS 10.14, but we've encountered operational issues on MacOS 10.15. Given the trend, we expect these problems to worsen with newer MacOS versions. We strongly recommend migrating to the Linux version of GONE, as we are moving towards discontinuing updates and support for the MacOS version.

Best,

Enrique
