### ISSUE TITLE
Got signal 11 error when analyzing my test data

### ISSUE THREAD

**Issue by taishudayo** [esrud/GONE#4]
Hi
I'm trying to use GONE on wsl2 Ubuntu20.04 for my SNP .ped&.map  test file obtained from 24ind RAD-seq. 
I can run the program with attacthed example data successfully by the command "bash script_GONE.sh example", but I can't run with my data. 
Below is the output and error I obtained : 
  DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 2 seconds
Running GONE
xargs: bash: terminated by signal 11
xargs: bash: terminated by signal 11
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv:cannot stat 'outfileLD_d2_sample': No such file or directory

please help me...

Taishu

**Comment by esrud** [comment]
Hi Taishu,

Probably your map or ped files have format errors. Do you want me to have a look at those files?

Best,

Enrique

**Comment by taishudayo** [comment]
Hi Enrique

Thanks for your fast replying!
Because I didin't know how to uploading file to this github forum, I sent E-mail to you yesterday with the files I actually used. 
But now, I know the way of uploading.  So please check it if you have time.
(The .ped and .map format are not allowed, so I temporally convert them to .txt)
[Tf_RAD_R0.8_Stacks_plinkver.map.txt](https://github.com/esrud/GONE/files/7984439/Tf_RAD_R0.8_Stacks_plinkver.map.txt)
[Tf_RAD_R0.8_Stacks_plinkver.ped.txt](https://github.com/esrud/GONE/files/7984441/Tf_RAD_R0.8_Stacks_plinkver.ped.txt)



After receiving your replying, I also completed genotyping from GATK pipeline.
So I used another ped & map file generated from GATK pipeline to run the GONE, but the same error was gained...
[Tf_RAD_GATK_vcftoolsver.map.txt](https://github.com/esrud/GONE/files/7984406/Tf_RAD_GATK_vcftoolsver.map.txt)
[Tf_RAD_GATK_vcftoolsver.ped.txt](https://github.com/esrud/GONE/files/7984408/Tf_RAD_GATK_vcftoolsver.ped.txt)

When I convert vcf to ped & map, I tried both converting  methods of plink and vcftools.
But neither outputs did work.

Plese help me if you have time...

Best, 

Taishu

**Comment by taishudayo** [comment]
Hi Enrique

I still don't know what surely caused the error I said above, but I found a solution.
The program worked well for some reason in my new workstation comprised of pure Linux system (Ubuntu).
So now I can only say that the error caused due to some system environmental difference between pure Linux and windows subsystems for Linux. (Or some personal settings in my PC may just invent the program running...)
Anyway, Thank you very much for your reply and support!

Best,

Taishu

**Comment by sagitaninta** [comment]
I got the same error too but moving workstation is not a choice currently 🙃  so I am still appreciating much help on this.

I am currently trying GONE on a vcf file from one sample, made into .ped and .map by plink.

So the .map file looking like this
```
head RD21_auto.map
1 1_180830 0 180830
1 1_180860 0 180860
1 1_180895 0 180895
1 1_180996 0 180996
1 1_181005 0 181005
1 1_181041 0 181041
1 1_181403 0 181403
1 1_181428 0 181428
1 1_181432 0 181432
1 1_181498 0 181498
wc -l RD21_auto.map 
59461538 RD21_auto.map
```

And based on that, the ped file is looking like this
```
cut -f 1-20 RD21_auto.ped 
RD21    RD21    0       0       0       -9      G       C       A       G       A       G       A       G       G       C       G       T       A       G

```

I have copied the entire Linux directory from GONE to my running directory and this is how it runs:
```
bash script_GONE.sh RD21_auto
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
xargs: bash: terminated by signal 11
CHROMOSOME ANALYSES took 0 seconds
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory
```

Is there any idea on where I can start debugging this? Perhaps GONE cannot work with one individual only?

**Comment by armando-caballero** [comment]
*Perhaps GONE cannot work with one individual only?*
No, you cannot get LD estimates with only one individual. Minimum two.
Best wishes,
Armando.

**Comment by sagitaninta** [comment]
Hey Armando, thanks for answering this! I was just realizing that after trying more things and reading more issues and have deleted the message, but thank you anyway.
