### ISSUE TITLE
Error running macOS example data: example.ped not being read correctly?

### ISSUE THREAD

**Issue by Ali-Hudson** [esrud/GONE#43]
Hi there. I have just downloaded the MacOSX version, but I am encountering an issue when attempting to run the example in which it appears the .map file is read but example.ped is not being read in and interpretted correctly. 

All files and the contents of PROGRAMMES have been given full permissions and I've dealt with all the security warnings. 

When I run the example, this is what the on-screen output looks like:

```
bash script_GONE.sh example
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 1 seconds
Running GONE
 Too few bins.
 Too few bins.
         ...
 Too few bins.
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: rename outfileLD_Ne_estimates to Output_Ne_example: No such file or directory
mv: rename outfileLD_d2_sample to Output_d2_example: No such file or directory
```

OUTPUT_example looks like this:

```
TOTAL NUMBER OF SNPs
0


HARDY-WEINBERG DEVIATION
nan       Hardy-Weinberg deviation (sample)
nan       Hardy-Weinberg deviation (population)


CHROMOSOME 1
 NIND(real sample)=0
 NSNP=10239
 NSNP_calculations=0
 NSNP_+2alleles=0
 NSNP_zeroes=0
 NSNP_monomorphic=10239
 NIND_corrected=nan
 freq_MAF=1.000000
 F_dev_HW (sample)=nan
 F_dev_HW (pop)=nan
 Genetic distances available in map file

CHROMOSOME 2
 NIND(real sample)=0
 NSNP=9351
 NSNP_calculations=0
 NSNP_+2alleles=0
 NSNP_zeroes=0
 NSNP_monomorphic=9351
 NIND_corrected=nan
 freq_MAF=1.000000
 F_dev_HW (sample)=nan
 F_dev_HW (pop)=nan
 Genetic distances available in map file 
 
.... # all the way to chr10 which looks similar

INPUT FOR GONE


2       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)
nan       sample size (individuals; corrected for zeroes)
nan       Hardy-Weinberg deviation
```

In TEMPORARY FILES, the per-chromosome .ped and .map files have been created, but the .peds are all empty.
This results in outfiles that look like this:

```
 head outfileLD1 
2
-99
-99
0 0 0 2 0 0
0 0 0 4 0 0
0 0 0 6 0 0
0 0 0 8 0 0
0 0 0 10 0 0
0 0 0 15 0 0
0 0 0 20 0 0
```

and outfileLD_TEMP is empty.

The timefile just contains this:
```
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES
CHROMOSOME ANALYSES took 0 seconds
Running GONE
GONE run took 1 seconds
END OF ANALYSES
```

The example.ped looks normal to me at a glance ` 1 IND1 0 0 1 -9 A A A A A T A A T A A A T  `  ...

Can anyone give me a hand? Am I the only person who's experienced this issue?

**Comment by Ali-Hudson** [comment]
I've also tried duplicating and renaming both example files in case there's some hidden character different in the names but that didn't change anything either...

**Comment by Ali-Hudson** [comment]
And I've tried downloading the example data for Linux and running that on my Mac with the same results.

**Comment by esrud** [comment]
GONE encounters issues when running on macOS versions later than 10.15. Consequently, the macOS version of GONE will be discontinued in the future. We recommend the Linux version instead.

Best,

De: Ali-Hudson ***@***.***>
Fecha: jueves, 6 de junio de 2024, 12:05
Para: esrud/GONE ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [esrud/GONE] Error running macOS example data: example.ped not being read correctly? (Issue #43)

Hi there. I have just downloaded the MacOSX version, but I am encountering an issue when attempting to run the example in which it appears the .map file is read but example.ped is not being read in and interpretted correctly.

All files and the contents of PROGRAMMES have been given full permissions and I've dealt with all the security warnings.

When I run the example, this is what the on-screen output looks like:

bash script_GONE.sh example

DIVIDE .ped AND .map FILES IN CHROMOSOMES

RUNNING ANALYSIS OF CHROMOSOMES ...

CHROMOSOME ANALYSES took 1 seconds

Running GONE

 Too few bins.

 Too few bins.

         ...

 Too few bins.

  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest

 END OF ALL PROCESSES

GONE run took 0 seconds

END OF ANALYSES

mv: rename outfileLD_Ne_estimates to Output_Ne_example: No such file or directory

mv: rename outfileLD_d2_sample to Output_d2_example: No such file or directory

OUTPUT_example looks like this:

TOTAL NUMBER OF SNPs

0





HARDY-WEINBERG DEVIATION

nan       Hardy-Weinberg deviation (sample)

nan       Hardy-Weinberg deviation (population)





CHROMOSOME 1

 NIND(real sample)=0

 NSNP=10239

 NSNP_calculations=0

 NSNP_+2alleles=0

 NSNP_zeroes=0

 NSNP_monomorphic=10239

 NIND_corrected=nan

 freq_MAF=1.000000

 F_dev_HW (sample)=nan

 F_dev_HW (pop)=nan

 Genetic distances available in map file



CHROMOSOME 2

 NIND(real sample)=0

 NSNP=9351

 NSNP_calculations=0

 NSNP_+2alleles=0

 NSNP_zeroes=0

 NSNP_monomorphic=9351

 NIND_corrected=nan

 freq_MAF=1.000000

 F_dev_HW (sample)=nan

 F_dev_HW (pop)=nan

 Genetic distances available in map file



.... # all the way to chr10 which looks similar



INPUT FOR GONE





2       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)

nan       sample size (individuals; corrected for zeroes)

nan       Hardy-Weinberg deviation

In TEMPORARY FILES, the per-chromosome .ped and .map files have been created, but the .peds are all empty.
This results in outfiles that look like this:

 head outfileLD1

2

-99

-99

0 0 0 2 0 0

0 0 0 4 0 0

0 0 0 6 0 0

0 0 0 8 0 0

0 0 0 10 0 0

0 0 0 15 0 0

0 0 0 20 0 0

and outfileLD_TEMP is empty.

The timefile just contains this:

DIVIDE .ped AND .map FILES IN CHROMOSOMES

RUNNING ANALYSIS OF CHROMOSOMES

CHROMOSOME ANALYSES took 0 seconds

Running GONE

GONE run took 1 seconds

END OF ANALYSES

The example.ped looks normal to me at a glance 1 IND1 0 0 1 -9 A A A A A T A A T A A A T ...

Can anyone give me a hand? Am I the only person who's experienced this issue?
