### ISSUE TITLE
GONE not running: Says too few bins 

### ISSUE THREAD

**Issue by mwersebe** [esrud/GONE#6]
Hi, 
I am trying to get GONE to run on input SNP data. 

Each time I run the program, it runs the split chromosome part of the program. When it switches to run GONE is prints to screen that there are too few bins to analyze. The input file included defaults. 

I am guessing that the input parameters NGEN and NBIN should be optimized in some way. Any suggestions to adjust the input parameters to run the NE estimation?

Thanks!

**Comment by armando-caballero** [comment]
Dear Matt,
Please give me (armando@uvigo.es) info on your data (number of SNPs, individuals, etc.) to see what is the problem. Alternatively, if you want to send me the map and ped files I will have a look to see what is the problem.
Best wishes,
Armando.

**Comment by armando-caballero** [comment]
I forgot to say that I tried to increase the number of bins by using:

NGEN=200 ### Number of generations for which linkage data is obtained in bins
NBIN=200  ### Number of bins (e.g. 1000, so that each bin includes NGEN/NBIN generations)

However, the number of bins remains being low.
Armando.
