### ISSUE TITLE
error xargs bash terminated by signal 11

### ISSUE THREAD

**Issue by hmoral** [esrud/GONE#7]
Hi,

I got a WGS bird dataset with 21 individuals mapped to a chromosome-level assembly of a close relative with ~22 million SNPs. I'm getting the following error:

xargs: bash: terminated by signal 11
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD Format error in file outfileLD

I think it is NOT a problem with the format of the plink files because if I subset one chromosome at a time those runs work well (although they don't give very sensible/consistent [results](https://www.dropbox.com/s/miykxnjcr5zl86q/0_plots.pdf?dl=0)). I can also run TWO chromosomes at one time

When I try to run a dataset with 5 or more chromosomes the error appears. Do you think it might be a memory issue? I have tried with 10 CPUS and a total of 40Gb

I can also filter the SNP dataset more aggressively, but I thought the parameters of max 50,000 SNP it would take care of that. 

Here my parameter file in case its relevant to asses the problem
```#INPUT_PARAMETERS_FILE

########################################################

PHASE=2 ### Phase = 0 (pseudohaploids), 1 (known phase), 2 (unknown phase)
cMMb=2  ### CentiMorgans per Megabase (if distance is not available).
DIST=1  ### none (0), Haldane correction (1) or Kosambi correction (2)
NGEN=2000 ### Number of generations for which linkage data is obtained in bins
NBIN=400  ### Number of bins (e.g. 1000, so that each bin includes NGEN/NBIN generations)
MAF=0.0   ### Minimum allele frequency (0-1)
ZERO=1    ### 0: Remove SNPs with zeroes (1: allow for them)
maxNCHROM=-99  ### Maximum number of chromosomes to be analysed (-99 = all chromosomes; maximum number is 200)
maxNSNP=50000 ### Maximum approx number of SNPs per chromosomes to be analysed (max is 100000)
hc=0.05   ### Maximum value of c analysed
REPS=40   ### Number of replicates to RUN GONE
threads=-99  ### Number of threads (if -99 it uses all possible processors)

###################################################################
```

**Comment by armando-caballero** [comment]
Dear Hernan,
I guess the problem is that 22 million SNPs are too many for GONE to handle it. Can you make a file with, say, 1 million SNPs and allow for 50,000 SNPs per chromosome (thus is more than enough). Please try with this and let me know how it goes then.
Armando.

**Comment by hmoral** [comment]
Thanks for the quick reply Armando,
You are right, it was the number of SNPs. I thought the max SNP parameter was taking care of this. But I now understand all the SNPs are first to read into the software and it is at this step that the problem arises.

**Comment by armando-caballero** [comment]
I correct my previous reply: you can use up to about 10 million SNPs in the map and ped files, but then use a maximum of about 50,000 per chromosome in each replicate estimation.
