### ISSUE TITLE
Wrong data type, strange sample size

### ISSUE THREAD

**Issue by OKersten** [esrud/GONE#8]
Hi,

I am encountering the same error message Wrong data type. Probably some input values are out of range

I pinpointed it to the fact that the outfileLD has -99 instead of 6 (sample size).
I have 6 individuals, 24 chromosomes, and a total of ca. 8M SNPs.
There is a few other things that don't seem to work as they should.

a) in the OUTPUT_* file, the total NSNPs is 2M. I don't have any monomorphic or missing SNPs though, so shouldn't it be 8M?
b) Chr 3-24 seem to work fine. Only 1 + 2 have strange sample sizes.
c) The corrected sample size in OUTPUT_* is negative for the troublesome chromosomes (1+2), whereas 6 for the rest (that is what it should be as I don't have monomorphic or missingness). I guess this is the reason for why b) is happening.
d) the first few lines of outfileLD* of some of the "working" chromosomes start as follows
```
2
6.000000
-0.120489
0 0 0 2 0 0
0 0 0 4 0 0
0 0 0 6 0 0
0 0 0 8 0 0
0 0 0 10 0 0
437780 0.034013 0.143440 15 0.003518 0.024526
```
Is it "normal" to have lines begin with 3 zeros?

I attached all files to potentially recreate the issue (name of pop is SPI). Except for the .map and .ped as they are too big too attach to this post,

Thanks for any help!
[INPUT_PARAMETERS_FILE.txt](https://github.com/esrud/GONE/files/8476597/INPUT_PARAMETERS_FILE.txt)
[outfileLD1.txt](https://github.com/esrud/GONE/files/8476598/outfileLD1.txt)
[outfileLD7.txt](https://github.com/esrud/GONE/files/8476599/outfileLD7.txt)
[outfileLD24.txt](https://github.com/esrud/GONE/files/8476600/outfileLD24.txt)
[OUTPUT_SPI.txt](https://github.com/esrud/GONE/files/8476601/OUTPUT_SPI.txt)

**Comment by armando-caballero** [comment]
Dear OKersten,
I reply to your queries:

> I pinpointed it to the fact that the outfileLD has -99 instead of 6 (sample size).
There must be some error in the input data file. A -99 should not appear there.

> in the OUTPUT_* file, the total NSNPs is 2M. I don't have any monomorphic or missing SNPs though, so shouldn't it be 8M?
Although you have 8M, because you are using a maximum of 50,000 per chromosome, the number of SNPs for analysis should be a maximum of 24 chr x 50,000 snps = about 1,2 M 
 
>Chr 3-24 seem to work fine. Only 1 + 2 have strange sample sizes ... The corrected sample size in OUTPUT_* is negative for the troublesome chromosomes (1+2), whereas 6 for the rest
Yes, this looks like a format problem in the input data of those chromosomes 1 and 2.

> Is it "normal" to have lines begin with 3 zeros?
Yes, this is normal. If the chromosome is small, there may not be SNPs at large genetic distances and, therefore, there are not pairs of SNPs at the upper bins.

To see what is going on with your data I would need a map and ped file. Perhaps you can send me (armando@uvigo.es) a reduced set one, with say 50,000 SNPs per chromosome, where you get the same problems.

Note that we have included now a Tutorial in the page, where some of the common queries are answered.
 
Best wishes,
Armando.

**Comment by armando-caballero** [comment]
Dear OKersten,
A question: How many SNPs are in chromosomes 1 and 2?
Some problems arise because there are too many SNPs in the data to be handled.
Try to reduce (at random) the number of SNPs in these chromosomes.
Armando.

**Comment by OKersten** [comment]
Hi Armando, thanks for the super quick reply. 

Chromosome 1 and 2 had ca 1.5M SNPs whereas Chromosome 3 and higher had < 1M SNPs. 

What I am still confused by is in the OUTPUT_SPI.txt (attached earlier) that, for e.g. Chromosome 3 (which seemingly worked), it says 
```
NSNP=61012
NSNP_calculations=61012

```
I specified 50,000 in the InputParameter file. Should `NSNP_calculations=` not be 50k then?

Chromosome 3 has actually 943,482 SNPs, so does the output also seem uncorrect/faulty? 
From the tutorial I understood that NSNP should maybe be the actual number (943,482) whereas NSNP_calculations should be the ca. 50k SNP specified in the InputParameter.

I will now try and downsampled Chr1 and Chr 2 and see if that helps, although I am wondering whether I need prior downsampling for more than just those 2 chromosomes.

**Comment by OKersten** [comment]
OK thanks for the clarification. I now downsampled all Chrs to a max of 500M SNPs and everything worked well!

Cheers
